// <auto-generated />
using KutuphaneSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KutuphaneSistemi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260511151050_DahaFazlaVeriVeGorsellestirme")]
    partial class DahaFazlaVeriVeGorsellestirme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KutuphaneSistemi.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Türk yazar ve şair. Kürk Mantolu Madonna başta olmak üzere pek çok önemli eser kaleme almıştır.",
                            BirthYear = 1907,
                            Country = "Türkiye",
                            FullName = "Sabahattin Ali"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Nobel Edebiyat Ödülü'ne aday gösterilen Türk yazar. İnce Memed romanıyla dünya çapında ün kazanmıştır.",
                            BirthYear = 1923,
                            Country = "Türkiye",
                            FullName = "Yaşar Kemal"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "İngiliz yazar ve gazeteci. 1984 ve Hayvan Çiftliği adlı distopik romanlarıyla tanınmaktadır.",
                            BirthYear = 1903,
                            Country = "Birleşik Krallık",
                            FullName = "George Orwell"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Türk romancı, milliyetçi ve feminist. Kurtuluş Savaşı'nın önemli isimlerinden biridir.",
                            BirthYear = 1884,
                            Country = "Türkiye",
                            FullName = "Halide Edib Adıvar"
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Nobel Edebiyat Ödülü sahibi Türk yazar. Benim Adım Kırmızı ve Kar başlıca eserleri arasındadır.",
                            BirthYear = 1952,
                            Country = "Türkiye",
                            FullName = "Orhan Pamuk"
                        },
                        new
                        {
                            Id = 6,
                            Biography = "Rus edebiyatının büyük ustalarından biri. Suç ve Ceza ile Karamazov Kardeşler başyapıtlarıdır.",
                            BirthYear = 1821,
                            Country = "Rusya",
                            FullName = "Fyodor Dostoyevski"
                        },
                        new
                        {
                            Id = 7,
                            Biography = "Varoluşçu ve absürd edebiyatın öncüsü. Dönüşüm ve Dava en çok okunan eserleridir.",
                            BirthYear = 1883,
                            Country = "Avusturya-Macaristan",
                            FullName = "Franz Kafka"
                        },
                        new
                        {
                            Id = 8,
                            Biography = "Fransız romantizm akımının önde gelen yazarı. Sefiller ve Notre-Dame'ın Kamburu başlıca eserleridir.",
                            BirthYear = 1802,
                            Country = "Fransa",
                            FullName = "Victor Hugo"
                        },
                        new
                        {
                            Id = 9,
                            Biography = "Avusturyalı yazar. Psikolojik derinliğiyle tanınan Satranç ve kısa hikayeleriyle ünlüdür.",
                            BirthYear = 1881,
                            Country = "Avusturya",
                            FullName = "Stefan Zweig"
                        },
                        new
                        {
                            Id = 10,
                            Biography = "İngiliz romancı. Toplumsal eleştiri ve ince mizahıyla Gurur ve Önyargı başyapıt kabul edilir.",
                            BirthYear = 1775,
                            Country = "Birleşik Krallık",
                            FullName = "Jane Austen"
                        },
                        new
                        {
                            Id = 11,
                            Biography = "İngiliz yazar. Harry Potter serisiyle dünya çapında milyonlarca okuyucuya ulaşmıştır.",
                            BirthYear = 1965,
                            Country = "Birleşik Krallık",
                            FullName = "J.K. Rowling"
                        },
                        new
                        {
                            Id = 12,
                            Biography = "Victorian dönem İngilteresi'ni anlatan romanlarıyla tanınan İngiliz yazar. Oliver Twist ve İki Şehrin Hikayesi önemli eserleridir.",
                            BirthYear = 1812,
                            Country = "Birleşik Krallık",
                            FullName = "Charles Dickens"
                        },
                        new
                        {
                            Id = 13,
                            Biography = "Amerikalı yazar. Jazz Çağı'nı en iyi anlatan roman olan Büyük Gatsby'nin yazarıdır.",
                            BirthYear = 1896,
                            Country = "Amerika Birleşik Devletleri",
                            FullName = "F. Scott Fitzgerald"
                        },
                        new
                        {
                            Id = 14,
                            Biography = "Amerikalı yazar ve sosyalist aktivist. Doğa ve hayatta kalma temalarını işleyen Martin Eden ve Vahşetin Çağrısı önemli eserleridir.",
                            BirthYear = 1876,
                            Country = "Amerika Birleşik Devletleri",
                            FullName = "Jack London"
                        });
                });

            modelBuilder.Entity("KutuphaneSistemi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("ShelfLocation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 3,
                            ISBN = "978-975-10-0001-1",
                            IsAvailable = true,
                            PageCount = 152,
                            PublicationYear = 1943,
                            ShelfLocation = "A-01",
                            Title = "Kürk Mantolu Madonna"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 3,
                            ISBN = "978-975-10-0002-2",
                            IsAvailable = true,
                            PageCount = 408,
                            PublicationYear = 1955,
                            ShelfLocation = "A-02",
                            Title = "İnce Memed"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CategoryId = 2,
                            ISBN = "978-975-10-0003-3",
                            IsAvailable = false,
                            PageCount = 112,
                            PublicationYear = 1945,
                            ShelfLocation = "B-01",
                            Title = "Hayvan Çiftliği"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            CategoryId = 2,
                            ISBN = "978-975-10-0004-4",
                            IsAvailable = true,
                            PageCount = 352,
                            PublicationYear = 1949,
                            ShelfLocation = "B-02",
                            Title = "1984"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 4,
                            CategoryId = 3,
                            ISBN = "978-975-10-0005-5",
                            IsAvailable = true,
                            PageCount = 320,
                            PublicationYear = 1936,
                            ShelfLocation = "A-03",
                            Title = "Sinekli Bakkal"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            CategoryId = 3,
                            ISBN = "978-975-10-0006-6",
                            IsAvailable = true,
                            PageCount = 200,
                            PublicationYear = 1940,
                            ShelfLocation = "A-04",
                            Title = "İçimizdeki Şeytan"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 5,
                            CategoryId = 3,
                            ISBN = "978-975-10-0007-7",
                            IsAvailable = false,
                            PageCount = 417,
                            PublicationYear = 1998,
                            ShelfLocation = "A-05",
                            Title = "Benim Adım Kırmızı"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 5,
                            CategoryId = 1,
                            ISBN = "978-975-10-0008-8",
                            IsAvailable = true,
                            PageCount = 479,
                            PublicationYear = 2002,
                            ShelfLocation = "A-06",
                            Title = "Kar"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 6,
                            CategoryId = 5,
                            ISBN = "978-975-10-0009-9",
                            IsAvailable = true,
                            PageCount = 671,
                            PublicationYear = 1866,
                            ShelfLocation = "C-01",
                            Title = "Suç ve Ceza"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 6,
                            CategoryId = 5,
                            ISBN = "978-975-10-0010-0",
                            IsAvailable = false,
                            PageCount = 924,
                            PublicationYear = 1880,
                            ShelfLocation = "C-02",
                            Title = "Karamazov Kardeşler"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 6,
                            CategoryId = 5,
                            ISBN = "978-975-10-0011-1",
                            IsAvailable = true,
                            PageCount = 144,
                            PublicationYear = 1848,
                            ShelfLocation = "C-03",
                            Title = "Beyaz Geceler"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 7,
                            CategoryId = 5,
                            ISBN = "978-975-10-0012-2",
                            IsAvailable = true,
                            PageCount = 192,
                            PublicationYear = 1925,
                            ShelfLocation = "C-04",
                            Title = "Dava"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 7,
                            CategoryId = 5,
                            ISBN = "978-975-10-0013-3",
                            IsAvailable = false,
                            PageCount = 96,
                            PublicationYear = 1915,
                            ShelfLocation = "C-05",
                            Title = "Dönüşüm"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 8,
                            CategoryId = 5,
                            ISBN = "978-975-10-0014-4",
                            IsAvailable = true,
                            PageCount = 1232,
                            PublicationYear = 1862,
                            ShelfLocation = "D-01",
                            Title = "Sefiller"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 8,
                            CategoryId = 5,
                            ISBN = "978-975-10-0015-5",
                            IsAvailable = true,
                            PageCount = 536,
                            PublicationYear = 1831,
                            ShelfLocation = "D-02",
                            Title = "Notre-Dame'ın Kamburu"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 9,
                            CategoryId = 5,
                            ISBN = "978-975-10-0016-6",
                            IsAvailable = true,
                            PageCount = 128,
                            PublicationYear = 1942,
                            ShelfLocation = "D-03",
                            Title = "Satranç"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 9,
                            CategoryId = 9,
                            ISBN = "978-975-10-0017-7",
                            IsAvailable = false,
                            PageCount = 80,
                            PublicationYear = 1922,
                            ShelfLocation = "D-04",
                            Title = "Bilinmeyen Bir Kadının Mektubu"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 10,
                            CategoryId = 5,
                            ISBN = "978-975-10-0018-8",
                            IsAvailable = true,
                            PageCount = 432,
                            PublicationYear = 1813,
                            ShelfLocation = "E-01",
                            Title = "Gurur ve Önyargı"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 10,
                            CategoryId = 1,
                            ISBN = "978-975-10-0019-9",
                            IsAvailable = true,
                            PageCount = 474,
                            PublicationYear = 1815,
                            ShelfLocation = "E-02",
                            Title = "Emma"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 11,
                            CategoryId = 7,
                            ISBN = "978-975-10-0020-0",
                            IsAvailable = false,
                            PageCount = 223,
                            PublicationYear = 1997,
                            ShelfLocation = "E-03",
                            Title = "Harry Potter ve Felsefe Taşı"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 11,
                            CategoryId = 7,
                            ISBN = "978-975-10-0021-1",
                            IsAvailable = true,
                            PageCount = 251,
                            PublicationYear = 1998,
                            ShelfLocation = "E-04",
                            Title = "Harry Potter ve Sırlar Odası"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 12,
                            CategoryId = 5,
                            ISBN = "978-975-10-0022-2",
                            IsAvailable = true,
                            PageCount = 448,
                            PublicationYear = 1859,
                            ShelfLocation = "E-05",
                            Title = "İki Şehrin Hikayesi"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 13,
                            CategoryId = 5,
                            ISBN = "978-975-10-0023-3",
                            IsAvailable = false,
                            PageCount = 180,
                            PublicationYear = 1925,
                            ShelfLocation = "F-01",
                            Title = "Büyük Gatsby"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 14,
                            CategoryId = 5,
                            ISBN = "978-975-10-0024-4",
                            IsAvailable = true,
                            PageCount = 411,
                            PublicationYear = 1909,
                            ShelfLocation = "F-02",
                            Title = "Martin Eden"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 14,
                            CategoryId = 1,
                            ISBN = "978-975-10-0025-5",
                            IsAvailable = true,
                            PageCount = 172,
                            PublicationYear = 1903,
                            ShelfLocation = "F-03",
                            Title = "Vahşetin Çağrısı"
                        });
                });

            modelBuilder.Entity("KutuphaneSistemi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Uzun anlatı türündeki kurgu eserleri",
                            Name = "Roman"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Siyasi temalar içeren kurgu eserleri",
                            Name = "Siyasi Kurgu"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Türk yazarların kaleme aldığı edebiyat eserleri",
                            Name = "Türk Edebiyatı"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Dünya edebiyatının klasik sayılan eserleri",
                            Name = "Klasik Edebiyat"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Farklı ülkelerden dünya edebiyatına mal olmuş başyapıtlar",
                            Name = "Dünya Klasikleri"
                        },
                        new
                        {
                            Id = 6,
                            Description = "İnsan psikolojisini ve iç dünyasını ön plana çıkaran eserler",
                            Name = "Psikoloji"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Büyü, mitoloji ve hayali dünyaları konu alan eserler",
                            Name = "Fantezi"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Tarihsel olayları ve dönemleri anlatan eserler",
                            Name = "Tarih"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Duygusal yoğunluğu ve insani çatışmaları ele alan eserler",
                            Name = "Drama"
                        });
                });

            modelBuilder.Entity("KutuphaneSistemi.Models.Book", b =>
                {
                    b.HasOne("KutuphaneSistemi.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KutuphaneSistemi.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("KutuphaneSistemi.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("KutuphaneSistemi.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
