// <auto-generated />
using KutuphaneSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KutuphaneSistemi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KutuphaneSistemi.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Türk yazar ve şair. Kürk Mantolu Madonna başta olmak üzere pek çok önemli eser kaleme almıştır.",
                            BirthYear = 1907,
                            Country = "Türkiye",
                            FullName = "Sabahattin Ali"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Nobel Edebiyat Ödülü'ne aday gösterilen Türk yazar. İnce Memed romanıyla dünya çapında ün kazanmıştır.",
                            BirthYear = 1923,
                            Country = "Türkiye",
                            FullName = "Yaşar Kemal"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "İngiliz yazar ve gazeteci. 1984 ve Hayvan Çiftliği adlı distopik romanlarıyla tanınmaktadır.",
                            BirthYear = 1903,
                            Country = "Birleşik Krallık",
                            FullName = "George Orwell"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Türk romancı, milliyetçi ve feminist. Kurtuluş Savaşı'nın önemli isimlerinden biridir.",
                            BirthYear = 1884,
                            Country = "Türkiye",
                            FullName = "Halide Edib Adıvar"
                        });
                });

            modelBuilder.Entity("KutuphaneSistemi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("ShelfLocation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 3,
                            ISBN = "978-975-10-0001-1",
                            IsAvailable = true,
                            PageCount = 152,
                            PublicationYear = 1943,
                            ShelfLocation = "A-01",
                            Title = "Kürk Mantolu Madonna"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 3,
                            ISBN = "978-975-10-0002-2",
                            IsAvailable = true,
                            PageCount = 408,
                            PublicationYear = 1955,
                            ShelfLocation = "A-02",
                            Title = "İnce Memed"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CategoryId = 2,
                            ISBN = "978-975-10-0003-3",
                            IsAvailable = false,
                            PageCount = 112,
                            PublicationYear = 1945,
                            ShelfLocation = "B-01",
                            Title = "Hayvan Çiftliği"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            CategoryId = 2,
                            ISBN = "978-975-10-0004-4",
                            IsAvailable = true,
                            PageCount = 352,
                            PublicationYear = 1949,
                            ShelfLocation = "B-02",
                            Title = "1984"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 4,
                            CategoryId = 3,
                            ISBN = "978-975-10-0005-5",
                            IsAvailable = true,
                            PageCount = 320,
                            PublicationYear = 1936,
                            ShelfLocation = "A-03",
                            Title = "Sinekli Bakkal"
                        });
                });

            modelBuilder.Entity("KutuphaneSistemi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Uzun anlatı türündeki kurgu eserleri",
                            Name = "Roman"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Siyasi temalar içeren kurgu eserleri",
                            Name = "Siyasi Kurgu"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Türk yazarların kaleme aldığı edebiyat eserleri",
                            Name = "Türk Edebiyatı"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Dünya edebiyatının klasik sayılan eserleri",
                            Name = "Klasik Edebiyat"
                        });
                });

            modelBuilder.Entity("KutuphaneSistemi.Models.Book", b =>
                {
                    b.HasOne("KutuphaneSistemi.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KutuphaneSistemi.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("KutuphaneSistemi.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("KutuphaneSistemi.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
